### PR TITLE
Corrections, Restructure, easier building

### PR DESCRIPTION
**Pull request by kennylerma**
The is a big update and lots of restructuring.  Tests have now been moved to an Examples project.  The test project is now the beginnings of a Unit Test project for the library using Jasmine.  Building is much easier by selecting the document class in FlashDevelop and just building.  Also, you can select swc files for internal or external for the project within FlashDevelop.

### CODE REVIEW

**Comment by matrix3d** [comment]
good

**Comment by carlosrovira** [comment]
Hi @kennylerma, this huge refactor allows spriteflexjs be used with latest Apache Royale?
And other question. There's some maven work to build?
thanks for this effort! :)

**Comment by kennylerma** [comment]
@carlosrovira for the most part it works great with Royale 0.9.6.  However, there are still some issues The Box2D example won't build as the compiler throws a ton of errors, but some of it is just poorly written actionscript.  Additionally, in the TestVideo example.  The build is missing a dependency for MediaStreamConstraints which should be provided from the js.swc.  I'll likely add an issue for this. 

I haven't done any work with Maven, just updated the build scripts for this current project and started a unit testing project for it as well.  I need to generate some tutorials to show the current capabilities soon.

**Comment by matrix3d** [comment]
This is where I call the defect of royale. Because there is no good or bad code writing. A compiler should try to support all of these ways of writing. Because the compiler does not care about these underlying compilation issues. So our code changed a lot to be compatible with royale

**Comment by matrix3d** [comment]
Compilation error about box2d. This is where I call the defect of royale. Because there is no good or bad code writing. A compiler should try to support all of these ways of writing. Because the compiler does not care about these underlying compilation issues. So our code changed a lot to be compatible with royale

**Comment by carlosrovira** [comment]
@kennylerma great to see you reach that far! getting Royale 0.9.6 compatibility is a great milestone! :)
From there I'm sure you get the rest of points like Box2D
For Maven, I have lots of things on my plate but if anybody does this, hope I could do some day. But don't know when.

@matrix3d royale compiler is still changing, and this latest months there was many great changes done by @joshtynjala, @greg_dove and @aharui to name few. You always can update of fix more issues as you find them, is the only way to improve the compiler. There will be a time where we find very few things to fix or modify (hopefully).

**Comment by matrix3d** [comment]
Nice to see the progress of royale. I hope that one day I can have a really stable version.

**Comment by carlosrovira** [comment]
@matrix3d is up to all of us to get to that point :)

**Comment by Harbs** [comment]
What's the issue with Box2D? I don't see any compiler errors in that example (at least after fixing Stage in pull #24).

**Comment by matrix3d** [comment]
```
F:\proj\spriteflexjs\src\flash\display\Graphics.as line 27 column 3 错误: 在为以下对象生成代码时，ASBlockWalker 子系统中发生内部错误: F:\proj\spriteflexjs\src\flash\display\Graphics.as line 27 column 3: java.lang.ClassCastException: org.apache.royale.compiler.internal.tree.as.TypedExpressionNode cannot be cast to org.apache.royale.compiler.internal.tree.as.IdentifierNode
	at org.apache.royale.compiler.internal.semantics.SemanticUtils.resolveXML(SemanticUtils.java:994)
	at org.apache.royale.compiler.internal.codegen.js.JSEmitter.emitAssignmentCoercion(JSEmitter.java:539)
	at org.apache.royale.compiler.internal.codegen.js.jx.ClassEmitter.emitComplexInitializers(ClassEmitter.java:258)
	at org.apache.royale.compiler.internal.codegen.js.royale.JSRoyaleEmitter.emitComplexInitializers(JSRoyaleEmitter.java:777)
	at org.apache.royale.compiler.internal.codegen.js.royale.JSRoyaleEmitter.emitFunctionBlockHeader(JSRoyaleEmitter.java:429)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.visitBlock(ASBlockWalker.java:343)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:278)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:85)
	at org.apache.royale.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:110)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:159)
	at org.apache.royale.compiler.internal.codegen.as.ASEmitter.emitMethodScope(ASEmitter.java:867)
	at org.apache.royale.compiler.internal.codegen.js.jx.MethodEmitter.emit(MethodEmitter.java:145)
	at org.apache.royale.compiler.internal.codegen.js.royale.JSRoyaleEmitter.emitMethod(JSRoyaleEmitter.java:772)
	at org.apache.royale.compiler.internal.codegen.js.jx.ClassEmitter.emit(ClassEmitter.java:110)
	at org.apache.royale.compiler.internal.codegen.js.royale.JSRoyaleEmitter.emitClass(JSRoyaleEmitter.java:730)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.visitClass(ASBlockWalker.java:256)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:136)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:85)
	at org.apache.royale.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:110)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:159)
	at org.apache.royale.compiler.internal.codegen.js.goog.JSGoogEmitter.emitPackageContents(JSGoogEmitter.java:186)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.visitPackage(ASBlockWalker.java:244)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:132)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:85)
	at org.apache.royale.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:110)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:159)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.visitFile(ASBlockWalker.java:223)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeSwitch.handle(ASNodeSwitch.java:128)
	at org.apache.royale.compiler.internal.visitor.as.ASNodeHandler.handle(ASNodeHandler.java:85)
	at org.apache.royale.compiler.internal.visitor.as.BeforeAfterStrategy.handle(BeforeAfterStrategy.java:110)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.walk(ASBlockWalker.java:159)
	at org.apache.royale.compiler.internal.codegen.as.ASBlockWalker.visitCompilationUnit(ASBlockWalker.java:188)
	at org.apache.royale.compiler.internal.codegen.js.JSWriter.writeTo(JSWriter.java:96)
	at org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:409)
	at org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:263)
	at org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:220)
	at org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:367)
	at org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:302)
	at org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:260)
	at org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:242)
```

**Comment by matrix3d** [comment]
it is work now

**Comment by matrix3d** [comment]
@Harbs hi,http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs/lastSuccessfulBuild/artifact/out/apache-royale-0.9.6-bin-js.tar.gz the sdk can not work

**Comment by kennylerma** [comment]
Sorry guys, looks like when I merged master into mine something happened to updateStage as I had already changed this previously in my code.  

@Harbs The Box2D example does indeed compile.  However, I'm guessing you didn't view it in the browser as the console has tons of errors.  So, the result of the compile is incorrect.  Lack of Royale handling missing class constructors as part of the problem.

@matrix3d I agree the compiler should be able to handle the Box2D code as is.  The big one is the compiler complains of missing constructors. IMHO, it's poorly written to have so many classes in Box2D missing it's constructor as a matter of best practice.
```as3
b2World.as:577 Uncaught TypeError: this.m_contactManager.Collide is not a function
```

Spriteflexjs code had trouble with comments including certain characters or doc tags the compiler does recognize and created problems for closure compiler.

For the most part, my code update didn't need a whole lot of changes to make it work with the latest Royale.  The majority is cleanup and restructuring along with several bug fixes and additions.  Royale is by far more stable now, but I'm still seeing issues with dependencies that continues to be a show stopper.

**Comment by kennylerma** [comment]
I did a small test and it appears Royale does handle the missing class contructor as it should, but in the case of Box2D, I'm not sure what's happening.

**Comment by joshtynjala** [comment]
> Graphics.as line 27 column 3: java.lang.ClassCastException: org.apache.royale.compiler.internal.tree.as.TypedExpressionNode cannot be cast to org.apache.royale.compiler.internal.tree.as.IdentifierNode
>	at org.apache.royale.compiler.internal.semantics.SemanticUtils.resolveXML(SemanticUtils.java:994)
>	at org.apache.royale.compiler.internal.codegen.js.JSEmitter.emitAssignmentCoercion(JSEmitter.java:539)

This error is related to a part of the compiler that I changed recently. I should be able to fix this issue. I'll take a look soon!

**Comment by joshtynjala** [comment]
I was able to reproduce the "TypedExpressionNode cannot be cast to IdentifierNode" error when compiling the `TestBox2D` example. I fixed the bug in the compiler, and I can now successfully compile the `TextBox2D` example. My compiler changes should be available in a nightly build soon!

**Comment by kennylerma** [comment]
@joshtynjala that's great news.  I'll have look once the build goes through.

**Comment by matrix3d** [comment]
@joshtynjala 
Can you give me your sdk compilation address? I am not in a hurry to officially compile.

**Comment by joshtynjala** [comment]
Nightly builds are listed on the official download page:

https://royale.apache.org/download/

It may not include my changes yet. I saw a failed build on the CI server. Java crashed from low memory or something. It doesn't seem to have re-tried yet.

**Comment by matrix3d** [comment]
@joshtynjala  
i get this error.

Uncaught TypeError: Box2D.Common.Math.b2Vec2 is not a constructor
    at new Box2D.Common.Math.b2Sweep (TestBox2D.js:348)
    at new Box2D.Collision.b2TOIInput (TestBox2D.js:344)
    at TestBox2D.js:374
TestBox2D.js:2902 Uncaught TypeError: Cannot read property 'Sprite' of undefined
    at new TestBox2D (TestBox2D.js:2902)
    at index.html:11

**Comment by joshtynjala** [comment]
Using the latest nightly build, I see a similar error in the TestBox2D example.

```
TypeError: Box2D.Collision.Features is not a constructor
    at new Box2D.Collision.b2ContactID (Box2D/Collision/b2ContactID.js:21:19)
    at new Box2D.Collision.b2ContactPoint (Box2D/Collision/b2ContactPoint.js:24:11)
    at Box2D/Dynamics/b2ContactManager.js:115:44
```

This appears to be a bug in remove-circulars. Unfortunately, that's not a part of the compiler code that I know well. Alex Harui will probably need to fix it.

**Comment by carlosrovira** [comment]
Hi Josh,
don't know if @aharui is tracking this (GitHub doesn't recognize his user in this thread, so I'm pretty sure he doesn't know about this). If not you or @matrix3d should warn him about the issue.

**Comment by matrix3d** [comment]
This is my concern about this sdk. This box2d, flexjs has been compiled. But this new royale can't be compiled yet!!? . Then I looked at the compiled js code and felt that the quality of the compilation was very poor.
```
this.flash___native_GLCanvasRenderingContext2D_matrhelp.copyFrom(posmatr);
        this.flash___native_GLCanvasRenderingContext2D_matrhelp.invert();
        this.flash___native_GLCanvasRenderingContext2D_matrhelp.concat(uvmatr);
        this.flash___native_GLCanvasRenderingContext2D_matrhelp.b *= -1;
        this.flash___native_GLCanvasRenderingContext2D_matrhelp.c *= -1;
        this.flash___native_GLCanvasRenderingContext2D_matrhelp.tx *= -1;
        this.flash___native_GLCanvasRenderingContext2D_matrhelp.ty *= -1;
```

 See why this code is not directly this.matrhelp? this.flash___native_GLCanvasRenderingContext2D_matrhelp , too long. There are too many details of this poor quality.
I know this library is a free project, and developers are working hard to develop. But the progress is too slow. Much worse than haxe js. And much worse than some new projects, ts, dark, kotlin. These languages ​​are developed after flexjs, but these language translation tools are beautifully translated. What worries me most is that sdk developers seem to be keen on mxml, not on the quality of as3 code. Although this library is still a beta version, it has been developed for quite some time.

**Comment by Harbs** [comment]
@matrix3d Those variables are there to support true private variables. In ActionScript it's possible to have a private variable in a superclass and the same variable name in a subclass. Without compiling unique private variable names, the two classes can step on each others' definitions.

Yes. It's "uglier" than the original names, but the variables should be renamed when minified and it serves an important function.

If you have a better idea, feel free to offer one.

**Comment by matrix3d** [comment]
Such long letters are hard to debug with Google. And in simple terms, you can judge whether there is a duplicate name, otherwise add the parent class to this

**Comment by joshtynjala** [comment]
I decided to play around with the Royale compiler and the Box2D example again today. I determined that this line in *b2ContactManager.as* is where the problem originates:

```actionscript
static private const s_evalCP:b2ContactPoint = new b2ContactPoint();
```

As a workaround, I found that I could change that line like this:

```actionscript
static private var s_evalCP:b2ContactPoint;
```

Then, I instantiated that object in the constructor instead:

```actionscript
public function b2ContactManager() {
	if(!s_evalCP)
	{
		s_evalCP = new b2ContactPoint()
	}
```

These changes got the example working for me.

As I mentioned earlier in the thread, I think that this is an issue with how `remove-circulars` works in the Royale compiler. The compiler does not currently understand that the `Box2D.Collision.Features` class needs to be loaded earlier in the process.

I found this comment in the compiler's GoogDepsWriter class:

```java
// first, promote all dependencies of classes used in static initializers to
// the level of static dependencies since their constructors will be
// run early.  This may need to be a full transitive walk someday.
// This is because we move many goog.requires from the various classes
// to the main app when removing circulars.  We only keep goog.requires
// that Closure Compiler cares about, which are requires for @extends
// and @implements.  However, as classes required by the application get
// loaded, their static initializers will fail if we haven't already goog.required
// the classes used by these static initializers, so we have to keep goog.requires
// used by these static initializers in the class files.
```

I suspect that we're running into the situation that "This may need to be a full transitive walk someday" refers to. The compiler has recognized that the `b2ContactPoint` class is needed for a static initializer, but it does not follow the dependencies far enough to recognize that the `Features` class is necessary too.

**Comment by matrix3d** [comment]
But this feature flexjs is supported. Why not change the compiler and change the code of Box2D. I think this Box2D code is written without problems.

**Comment by carlosrovira** [comment]
@matrix3d, if `const` was working and now is failing, that should be fixed since is part of AS3 language and spec. Maybe you can help in that rising hand in Apache Royale project or even submitting a patch for it.

**Comment by kennylerma** [comment]
I don't believe this is an issue with `const` but more with assigning static variables to a new instance outside of the constructor or initialization of the class.  I've ran into this issue, but have had to work around it to keep moving forward with my work.  I hadn't found this in Box2D, so thanks @joshtynjala .

@joshtynjala do you think you'll be able to fix this in the compiler?

**Comment by joshtynjala** [comment]
> Why not change the compiler and change the code of Box2D. I think this Box2D code is written without problems.

As I explained, this is a compiler bug, and the AS3 code that I posted is a workaround.

**Comment by joshtynjala** [comment]
> @joshtynjala do you think you'll be able to fix this in the compiler?

I'm not sure if I can fix it or not. The remove-circulars code is maintained by Alex Harui. I've read enough of that code to make a few minor tweaks here and there, but I don't know it as well as he does. I feel like I haven't seen any tests written for it either, so I may inadvertently break something if I'm not careful. However, Alex is going on vacation soon, and he was @ mentioned in this thread already with no response, so I think I may just need to dive in and figure it out.

**Comment by aharui** [comment]
There should be at least one section of code in the compiler that tries to detect "simple" static initializers so I am a bit surprised that initializing a static to "new someClass()" isn't working.  I am theoretically already on vacation so I'm trying to not look at source code and just point people in various directions.

**Comment by joshtynjala** [comment]
@aharui I understand, and I'll try to look into it.

Here's what I think is happening: When a static variable is instantiated with "new someClass()", "someClass" is also instantiating "new someOtherClass()" on a **non-static** variable. Normally, we ignore non-static variables, but "someClass" cannot be instantiated without "someOtherClass", so it needs to be prioritized like a static dependency.

**Comment by aharui** [comment]
The code snippet about

```static private const s_evalCP:b2ContactPoint = new b2ContactPoint();```

Is simple and should be handled correctly.  I'm pretty sure there are other usage of that pattern in code already.  But yes, any static initializers for b2ContactPoint may not get initialized in time, and that's the "transitive walk" mentioned in the comments you posted.

However, I'm not sure we can get a transitive walk to work correctly any time soon.  I think it would require running a JS interpreter.  Complex chains of static initializers may need to be re-coded in Royale.

FWIW, the remove-circular code is not maintained by me.  I do not "own" any code in Royale.  Others should not be assigning work to me.  Others should feel obligated to understand everyone else's code.  removeCirculars exists because of how Google Closure Compiler loads JS files.  Flex/Royale use a simple "1 public AS class outputs 1 JS file" approach, but that may be where the compiler needs to change for complex static initialization sequences.

These chains may need to be output into a single JS file with multiple goog.provides in them, or else maybe the compiler should just enforce Google's "no circular dependency" coding philosophy and force way more re-coding of existing AS code.

The emitters already try to detect static initialization and annotate the JS files to help the removeCirculars code.  Improvements there may also help since it may be possible to annotate more details at emitter time than to try to parse JS code at removeCircular time.

Another option is to have the compiler generate AVM-style static initialization emulation code for those who need it.

IMO, we have bigger priorities than trying to emulate AS static initialization in discrete JS files.  Some folks will have to re-code.

**Comment by joshtynjala** [comment]
> FWIW, the remove-circular code is not maintained by me. I do not "own" any code in Royale. Others should not be assigning work to me. Others should feel obligated to understand everyone else's code. 

No one is assigning work to you. You are the most experienced with this code, though, so there's nothing wrong with suggesting that you are most qualified to fix it. And, of course, you are welcome to not consider it a high priority. I'm going to try to fix it, as I've said several times now.

**Comment by Harbs** [comment]
@joshtynjala 
My suggestion (which I've made numerous times) to fix these initializations is to pull all non-native typed static initializations out into a separate file which is run after all class declarations.

That should (theoretically -- unless I'm mistaken) make figuring out dependencies for static initializations unnecessary considering all classes should have already been declared at the point the last file is evaluated.

**Comment by aharui** [comment]
The only concern I have with static initializations in a separate file is that it isn't PAYG.  I would think that EVERY static initializer in the app would be run before startup, which could be significantly different than how it works in a SWF.

If you had some Flex code where a static initializer initialized a table of data, that code would probably run after startup when/if you finally ran the code paths that actually used that class.  But in Royale that table initialization would run before startup, even if you never navigated to that part of the UI.

FWIW, in a SWF, the static initializers are all output in a function called something like SomeClass$$cinit().  So that part would be easy to do with the JS emitters.  But the problem is that the AVM's verifier is responsible for running the cinit().  I don't know of a way to know when to run the JS version of the cinit().  For simple scenarios, the constructor could have some code inserted into it like:

```
public function SomeClass()
{
   // inserted by compiler
  if (!SomeClass_cinited)
  {
     SomeClass_cinited = true;
     SomeClass_cinit();
  }
  // end code inserted by compiler
}

That would be PAYG.  I'm not sure how to handle "static-only" classes.  Maybe, like [Bindable] classes, all APIs are changed to getter/setters that run the cinit()

This would most closely emulate how static initializers get run in a SWF, and also not require gathering code across files.

**Comment by Harbs** [comment]
Fair enough, but it's no less PAYG than how it works now.

I'm also not sure the problem is just "static only" classes. It's possible for class A to access a static const on class B before any instance of class B is instantiated.

**Comment by joshtynjala** [comment]
Commit apache/royale-compiler@fd9e23730b4b6db512dc781b9dbbf644dc123e79 should fix the issue with the Box2D example.

**Comment by kennylerma** [comment]
Is this already in the latest builds from Jenkins?

**Comment by joshtynjala** [comment]
@kennylerma Yes, it should be.

**Comment by matrix3d** [comment]
Good. Next I will try to introduce a set of UI system. Mornui. Because mornui comes with a good UI editor.

**Comment by kennylerma** [comment]
@joshtynjala This works perfectly now.  Thank you so much for taking this on.

**Comment by matrix3d** [comment]
Uncaught TypeError: org.apache.royale.utils.Language.synthVector is not a function
    at new flash.geom.Matrix3D (Matrix3D.js:25)
    at Matrix3D.js:885

**Comment by matrix3d** [comment]
The box2d debug version is already available for generation. But the release version js is null

**Comment by joshtynjala** [comment]
Try to clean your project and build from scratch. You should always do this when you update to a new build of the SDK. Otherwise, you will have classes from the older SDK in your output folder, which may cause conflicts.

**Comment by matrix3d** [comment]
the warning make the js =null.
警告: F:/proj/spriteflexjs/examples/bin/js-debug/org/villekoskela/utils/RectanglePacker.js:205: WARNING - Parse error. illegal use of unknown JSDoc tag "width"; ignoring it
 * @width the width of inserted rectangle
   ^

八月 13, 2019 10:54:41 上午 com.google.javascript.jscomp.LoggerErrorManager println
警告: F:/proj/spriteflexjs/examples/bin/js-debug/org/villekoskela/utils/RectanglePacker.js:206: WARNING - Parse error. illegal use of unknown JSDoc tag "height"; ignoring it
 * @height the height of inserted rectangle
   ^

八月 13, 2019 10:54:41 上午 com.google.javascript.jscomp.LoggerErrorManager println
警告: F:/proj/spriteflexjs/examples/bin/js-debug/org/villekoskela/utils/RectanglePacker.js:413: WARNING - Parse error. illegal use of unknown JSDoc tag "width"; ignoring it
 * @width the width of inserted rectangle
   ^

八月 13, 2019 10:54:41 上午 com.google.javascript.jscomp.LoggerErrorManager println
警告: F:/proj/spriteflexjs/examples/bin/js-debug/org/villekoskela/utils/RectanglePacker.js:414: WARNING - Parse error. illegal use of unknown JSDoc tag "height"; ignoring it
 * @height the height of inserted rectangle
   ^

八月 13, 2019 10:54:41 上午 com.google.javascript.jscomp.LoggerErrorManager println
严重: ERROR - Cannot read file F:/proj/spriteflexjs/examples/bin/js-debug/flash/text/TextField.js: Failed to read: F:\proj\spriteflexjs\examples\bin\js-debug\flash\text\TextField.js, is this input UTF-8 encoded?

八月 13, 2019 10:54:41 上午 com.google.javascript.jscomp.LoggerErrorManager printSummary
警告: 1 error(s), 4 warning(s)

**Comment by matrix3d** [comment]
> Try to clean your project and build from scratch. You should always do this when you update to a new build of the SDK. Otherwise, you will have classes from the older SDK in your output folder, which may cause conflicts.

I should have cleaned up the cache, and I feel that this warning caused the compiler to fail to generate a release JS. So the compiler can ignore this warning

**Pull request merged**
