### PR TITLE
Fill / Line Gradients, cacheAsBitmap for Shape and Sprite, Video play…

### PR DESCRIPTION
**Pull request by kennylerma**
…back.  Bug fixes

This is a pretty sizable update.  Linear and Radial gradients have been added for Fill and Line.  Basic caching "cacheAsBitmap" for Shape and Sprite have been added to boost performance (See test "TestCaching").  Video has been added to demostrate URL playback, video bytes playback and Camera with motion detection (See "TestVideo").  Several bug fixes for Bounds, width, height and Matrix.  Also, I have adjusted the Test project to simply change the document class to run that specific test as release or debug.

### CODE REVIEW

**Comment by matrix3d** [comment]
nice job

**Comment by kennylerma** [comment]
Thanks, I'm looking at filters and masking next.  Of course this is all still just canvas, but I hope to add webgl versions at some point too.

**Comment by matrix3d** [comment]
If it can contain webgl curve rendering, it will be useful. Can support the swf format of the curve information. Several links can be referred to.
http://blog.bwhiting.co.uk/?p=423
https://css-tricks.com/rendering-svg-paths-in-webgl/
https://www.goodboydigital.com/pixijs/examples/21/

**Comment by kennylerma** [comment]
Thanks for the info.  I found this a while back too.  It's looks pretty good and very in depth.
http://labs.hyperandroid.com/efficient-webgl-stroking

**Pull request merged**
